name: Matrix Jobs

on: push

jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout-code
        run: actions/checkout@v3
      - name: Install NodeJS
        run: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install Dependency
        run: npm ci
      - name: Build Project
        run: npm run build